name: ConfigurationTests

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: restore NuGet packages
      run: nuget restore CDS.sln

    - name: build the solution
      run: msbuild CDS.sln