name: ConfigurationTests

on:
  push:
    branches:
      - "feature/*"
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.0

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore Packages
      run: nuget restore CDS.sln

    - name: Build Solution
      run: |
        msbuild.exe CDS.sln /p:platform="Any CPU" /p:configuration="Release"
        
    - name: Run Tests
      run: vstest.console.exe .\tests\CDS.Tests\bin\Release\CDS.Tests.dll
